sonar.projectKey=luxfoot
sonar.host.url=http://localhost:9000

sonar.sources=docs

sonar.exclusions=**/*.min.js,**.css
sonar.coverage.exclusions=**/*

sonar.sourceEncoding=UTF-8

sonar.issue.ignore.multicriteria=globalThis,cognitiveJs

sonar.issue.ignore.multicriteria.globalThis.ruleKey=javascript:S7764
sonar.issue.ignore.multicriteria.globalThis.resourceKey=**/*


sonar.issue.ignore.multicriteria.cognitiveJs.ruleKey=javascript:S3776
sonar.issue.ignore.multicriteria.cognitiveJs.resourceKey=**/*
sonar.issue.ignore.multicriteria.cognitiveJs.ruleParam.threshold=20
