teams={AAHE:"Alliance Aischdall Hobscheid/Eischen",ADUD:"Alliance Dudelange",AFLX:"Avenir Flaxweiler",AHOS:"AS Hosingen",ALLX:"Alliance 01 Luxemburg",
    AMRS:"Amis de la Moselle Remerschen",ARBD:"Arantia Berdorf",AREM:"AS Remich",ARIS:"Aris Bonnevoie",ASCB:"AS Colmar-Berg",ASCH:"AS Schifflange",
    ASDF:"AS Differdange",ASLX:"AS Luxembourg",ASTN:"Alisontia Steinsel",ATBS:"Atert Bissen",AVBG:"Avenir Beggen",AWDG:"Arminia Weidingen",BAST:"FC 47 Bastendorf",
    BBML:"Blue Boys Muhlenbach",BDBB:"Berdenia Berbourg",BENF:"RM Hamm Benfica",BIEK:"FC Biekerech",BGHP:"Blo-Giel Hupperdange",BGNV:"FC Bigonville",
    BLVL:"The Belval Belvaux",BOUS:"US Bous",BRAC:"Bracarense Grund",BRCH:"FC Brouch",BVAT:"US Boevange/Attert",BWIT:"Blo-Wäiss Itzig",BWMD:"Blo-Wäiss Medernach",
    BYUD:"FC Beyren-Udinesina",CBRA:"Cebra 01",CBSH:"CS Bourscheid",CECH:"CS Echternach",CESS:"Cessange FC",CGRV:"CS Grevenmacher",CLMC:"ES Clemency",
    CLVX:"Claravallis Clervaux",CMLB:"CS Mondorf-les-Bains",CSHL:"CS Hollerich",CPET:"CS Petange",CROD:"Chiers Rodange",CSOB:"CS Oberkorn",DARE:"Daring Club Echternach",
    DEIC:"Daring Club Eich",DIFF:"Differdange 03",DRZV:"Diables Rouges Zolver",ECBT:"Eclair Bettembourg",EBDU:"Etoile Bleu Dudelange",EGWM:"Egalité Weimerskirch",
    EHLR:"FC Ehlerange",ERDU:"Etoile Rouge 1908 Dudelange",ERPL:"FC Erpeldange 72",ESHW:"ES Schouweiler",ESLX:"Etoile Sportive Luxembourg",ETZE:"Etzella Ettelbréck",
    EXGV:"Excelsior Grevels",F91D:"F91 Dudelange",FBU1:"Flaxweiler/Beyren Udinesina 01",FCOB:"FC Oberkorn",FCPR:"FC Pratzerthal/Rédange",FOLA:"Fola Esch",
    FOLS:"US Folschette",FRTA:"Forta Beaufort",GBHT:"GB Harlange/Tarchamps",GDLL:"Grupo Desportivo dos Lusitanos de Larochette",GDUD:"Gallia Dudelange",
    GOLD:"Gold a Ro't Wiltz",GSWW:"Green Star Wilwerdingen",HAMM:"FC Hamm 37",HARL:"FC Harlange",HLBN:"US Hollerich/Bonnevoie",HOBS:"CS Hobscheid",
    HOST:"US Hostert",HUPP:"FC Hupperdange",ISKA:"Iska Boys Simmern",JBET:"Jeunesse Bettembourg",JBIW:"Jeunesse Biwer",JCNC:"Jeunesse Canach",JECT:"Jeunesse Echternach",
    JESH:"Jeunesse Esch",JGIL:"Jeunesse Gilsdorf",JHSD:"Jeunesse Heisdorf",JHTC:"Jeunesse Hautcharage",JKYL:"Jeunesse 07 Kayl",JOSP:"Jeunesse Ospern",
    JSCH:"Jeunesse Schieren",JSKH:"Jeunesse Sportive Koerich",JSTF:"Jeunesse Steinfort",JUNG:"Jeunesse Junglinster",JUSE:"Jeunesse Useldange",
    JVRL:"Jeunesse Verlorenkost",JWAS:"Jeunesse Wasserbillig",JWMK:"Jeunesse Weimerskirch",JWIL:"Jeunesse Wilwerdingen",KAER:"UN Käerjéng 97",KHLN:"FC Kehlen",
    KNAP:"FC Knaphoscheid/Selscheid",KOEP:"FC Koeppchen",KOPS:"FC Kopstal 33",KOSM:"FC Koerich",KPWW:"Kiischpelt Wilwerwiltz",KWRM:"Koeppchen Wormeldange",
    LADH:"Les Aiglons Dalheim",LARD:"Les Ardoisiers Perlé",LRNZ:"FC Lorentzweiler",LUNA:"Luna Oberkorn",LUXC:"FC Luxembourg City",MAMR:"Mamer 32",
    MANC:"Mansfeldia Clausen",MARM:"Marisca Mersch",MDCG:"FC Mondercange",MDLB:"US Mondorf-les-Bains",MGWW:"Les Montagnards Weiswampach",MINL:"Minerva Lintgen",
    MLSV:"Minière Lasauvage",MRTZ:"Sporting Mertzig",MUNS:"FC Munsbach",NESH:"National Esch",NORD:"FF Norden 02",NORZ:"FC Noertzange HF",NSCH:"National Schifflange",
    OBCN:"Old Boys Consdorf",OVND:"Orania Vianden",OYCW:"Olympia Christnach/Waldbillig",OYMP:"Olympique Äischen",PHLK:"Phalanx Kleinbettingen",PRTZ:"AS Pratzerthal",
    PROC:"Progrès Cessange",PROG:"Progrès Grund",PRON:"Progrès Niederkorn",RACE:"Racing Union",RACL:"Racing Club Luxembourg",RAMB:"US Rambrouch",RBAS:"Red Boys Aspelt",
    RBDF:"Red Boys Differdange",RBE7:"Red Black-Egalité 07",RBPF:"Red Black Pfaffenthal",REIS:"US Reisdorf",RHDS:"Racing Heiderscheid",RHSE:"Racing Heiderscheid/Eschdorf",
    RLCN:"Ro'de Le'w Consthum",RMHM:"FC RM Hamm Benfica",RMLX:"RM 86 Luxembourg",RODG:"FC Rodange 91",ROLG:"CS Rollingergrund",RPDN:"Rapid Neudorf",
    RPLL:"Rupensia Lusitanos Larochette",RROD:"Racing Rodange",RSMB:"Red Star Merl/Belair",RSML:"Red Star Merl",RUPL:"Rupensia Larochette",SAND:"US Sandweiler",
    SBCK:"Sporting Beckerich",SBRT:"Sporting Bertrange",SCBT:"SC Bettembourg",SCHF:"Schifflange 95",SCLX:"SC Luxembourg",SDIF:"SC Differdange",SDUD:"Stade Dudelange",
    SELL:"SC Ell",SHGN:"FC Schengen",SMOB:"Saint Michel Oberpallen",SNEM:"CS Sanem",SPDD:"Sparta Dudelange",SPOR:"Spora Luxembourg",SPST:"Sporting Steinfort",
    SRED:"SC Rédange",STNG:"FC Stengefort",STET:"SC Tétange",SURA:"Sura Esch/Sauer",SWFT:"Swift Hesperange",SYRA:"Syra Mensdorf",TLMD:"Titus Lamadelaine",
    TRIG:"Tricolore Gasperich",TRIM:"Tricolore Muhlenweg",TSVG:"Racing Troisvierges",TWTC:"Tarwat Tarchamps",U5KT:"Union 05 Kayl/Tétange",UBSH:"US Bascharage",
    UEDF:"US Eschdorf",UESH:"US Esch",UFLN:"US Feulen",ULUX:"Union Luxembourg",UMRT:"US Mertert",UNAS:"UNA Strassen",UNMW:"Union Mertert/Wasserbillig",
    UNRB:"Union Remich/Bous",UNTP:"Union Titus Petange",URUM:"US Rumelange",USBC:"US Berdorf/Consdorf",USDD:"US Dudelange",USMM:"US Moutfort/Medingen",
    USND:"US Niederwiltz",VICR:"Victoria Rosport",VINE:"Vinesca Ehnen",WALF:"Résidence Walferdange",WINC:"AS Wincrange",WLTZ:"FC Wiltz 71",WWMP:"FC Weiswampach",
    YBDK:"Young Boys Diekirch",YBWT:"Yellow Boys Weiler-la-Tour",YGGC:"Yougo Grund-Cessange",YBSW:"Young Boys Schweicherthal"};

function buildGraph() {
    leagueSizes = [];
	clubs = {};
	seasons = 0;

	function loadSeason1(t1=[]) {
		leagueSizes.push([t1.length]);
		loadSeason(t1,[],[],[],[]);
	}
	function loadSeason2(t1=[],t2=[]) {
		leagueSizes.push([t1.length,t2.length]);
		loadSeason(t1,t2,[],[],[]);
	}
	function loadSeason3(t1=[],t2=[],t3=[]) {
		leagueSizes.push([t1.length,t2.length,t3.length]);
		loadSeason(t1,t2,t3,[],[]);
	}
	function loadSeason4(t1=[],t2=[],t3=[],t4=[]) {
		leagueSizes.push([t1.length,t2.length,t3.length,t4.length]);
		loadSeason(t1,t2,t3,t4,[]);
	}
	function loadSeason5(t1=[],t2=[],t3=[],t4=[],t5=[]) {
		leagueSizes.push([t1.length,t2.length,t3.length,t4.length,t5.length]);
		loadSeason(t1,t2,t3,t4,t5);
	}
	function loadSeason6(t1=[],t2=[],t3=[],t4=[],t5=[],t6=[]) {
		leagueSizes.push([t1.length,t2.length,t3.length,t4.length,t5.length,t6.length]);
		loadSeason(t1,t2,t3,t4,t5,t6);
	}

	function loadSeason(t1=[],t2=[],t3=[],t4=[],t5=[],t6=[]) {
		p = 1;
		t1.forEach(c1=>{
			if ( !clubs[c1] ) {
				clubs[c1] = [];
				for ( i=1 ; i<=seasons ; i++ ) {
					clubs[c1].push( null );
				}
			}
			clubs[c1].push(p);
			p++;
		});
		t2.forEach(c2=>{
			c2.split("|").forEach(cc2=>{
				if ( !clubs[cc2] ) {
					clubs[cc2] = [];
					for ( i=1 ; i<=seasons ; i++ ) {
						clubs[cc2].push( null );
					}
				}
				clubs[cc2].push(p);
			});
			p++;
		});
		t3.forEach(c3=>{
			c3.split("|").forEach(cc3=>{
				if ( !clubs[cc3] ) {
					clubs[cc3] = [];
					for ( i=1 ; i<=seasons ; i++ ) {
						clubs[cc3].push( null );
					}
				}
				clubs[cc3].push(p);
			});
			p++;
		});
		t4.forEach(c4=>{
			c4.split("|").forEach(cc4=>{
				if ( !clubs[cc4] ) {
					clubs[cc4] = [];
					for ( i=1 ; i<=seasons ; i++ ) {
						clubs[cc4].push( null );
					}
				}
				clubs[cc4].push(p);
			});
			p++;
		});
		t5.forEach(c5=>{
			c5.split("|").forEach(cc5=>{
				if ( !clubs[cc5] ) {
					clubs[cc5] = [];
					for ( i=1 ; i<=seasons ; i++ ) {
						clubs[cc5].push( null );
					}
				}
				clubs[cc5].push(p);
			});
			p++;
		});
		t6.forEach(c6=>{
			c6.split("|").forEach(cc6=>{
				if ( !clubs[cc6] ) {
					clubs[cc6] = [];
					for ( i=1 ; i<=seasons ; i++ ) {
						clubs[cc6].push( null );
					}
				}
				clubs[cc6].push(p);
			});
			p++;
		});
		seasons ++;
		Object.keys(clubs).forEach(c=>{
			if ( clubs[c].length !== seasons ) {
				clubs[c].push( null );
			}
		});
	}

	/*1909-10*/ loadSeason1(["RACL","HLBN","SCLX","JESH","URUM","JECT","CROD","NESH","GDUD"]);
	/*1910-11*/ loadSeason1(["SCLX","SDIF","HLBN","MANC"]);
	/*1911-12*/ loadSeason1(["HLBN","SCLX","RACL","DEIC"]);
	/*1912-13*/ loadSeason1([]);
	/*1913-14*/ loadSeason1(["HLBN","SCLX","RACL","SDIF","JESH","CPET"]);
	/*1914-15*/ loadSeason1(["HLBN","SCLX|JESH|SDUD|CPET|YBDK","RACL|FOLA|USDD|SDIF|CECH"]);
	/*1915-16*/ loadSeason3(["HLBN","SCLX","FOLA","RACL","JESH","SDUD"],["YBDK","SDIF","CPET"],["CSHL|JBET","JSTF|NSCH","ROLG|ERDU"]);
	/*1916-17*/ loadSeason3(["HLBN","FOLA","RACL","SCLX","YBDK","JESH"],["CPET","SDIF","SDUD","CSHL","UESH"],["AVBG|URUM","JWMK|NSCH","WALF|STET","ROLG|BLVL"]);
	/*1917-18*/ loadSeason3(["FOLA","HLBN","SCLX","YBDK","RACL","CPET"],["JESH","SDIF","SDUD","URUM","CSHL"],["AVBG|STET","CMLB|ECBT","JWMK|NSCH","ADUD"]);
	/*1918-19*/ loadSeason3(["SCLX","FOLA","JESH","HLBN","RACL","YBDK"],["SDUD","SDIF","AVBG","URUM","CPET"],["CMLB|CROD","ETZE|NSCH","SWFT|ECBT","CLMC|STET","ADUD"]);
	/*1919-20*/ loadSeason3(["FOLA","SDUD","SCLX","HLBN","JESH","RACL"],["RBDF","URUM","NSCH","CROD","CPET","AVBG"],["PROG|BLVL|JSTF","TRIM|STET|PRON","MANC|ADUD|JHTC","CSHL|UESH|ETZE","JVRL|ECBT|CLMC","WALF","CMLB"]);
	/*1920-21*/ loadSeason4(["JESH","FOLA","HLBN","SDUD","RBDF","SCLX","RACL","URUM"],["TRIM","NSCH","CROD","PROG","CPET","JSTF","AVBG","BLVL"],["STET","UESH","PRON","CSHL","ADUD","MANC","ETZE","JHTC"],["RBPF|ECBT|FCOB","ASLX|USDD|OYMP","JWAS|IESH|BBOY","JVRL|ENFM|HAGN","MERL|JMON|YBSL","SWFT|JSNM"]);
	/*1921-22*/ loadSeason4(["FOLA","HLBN","JESH","SCLX","SDUD","RBDF","TRIM","NSCH"],["RACL","STET","URUM","CROD","CPET","PROG","UESH","JSTF"],["RBPF","ECBT","PRON","ADUD","BLVL","CSHL","AVBG","MANC"],["JWAS|USDD|JHTC|YBDK","RPDN|FCOB|HAGN|MARM","ASLX|JKYL|BBOY|MINL","WALF|ASDF|PHLK|ETZE","JVRL|YBSL|OYMP|GOLD","MERL|IESH|UBEK|USND","SWFT|JMON","SGRV|ENFM"]);
	/*1922-23*/ loadSeason4(["RBDF","SDUD","FOLA","JESH","HLBN","SCLX","RACL","STET"],["RBPF","ECBT","PROG","URUM","TRIM","CROD","NSCH","CPET"],["RPDN|USDD|PRON","JVRL|MANC|FCOB","YBDK|ADUD|UESH","CSHL|MARM|BLVL","JWAS|AVBG|JHTC"],["ASLX|ETZE|ASDF|JKYL","SGRV|GOLD|IESH|ROLG","RIEF|MINL|OYMP|HOPB","SWFT|BBOY|WALF"]);
	/*1923-24*/ loadSeason4(["FOLA","SPOR","RBDF","JESH","SDUD","HLBN","RBPF","ECBT"],["PROG","USDD","STET","URUM","PRON","CROD","RPDN","TRIM"],["YBDK|MANC|UESH","ETZE|ADUD|BLVL","ASLX|NSCH|CPET","SGRV|JKYL|ASDF","CSHL|JVRL|FCOB"],["MINL|AVBG|ARIS","RIEF|JHTC|SWFT","GOLD|UNAS|AZST","JWAS|OYMP|RSSW","SPST|ESLX","DARE"]);
	/*1924-25*/ loadSeason4(["SPOR","SDUD","JESH","FOLA","RBDF","HLBN","PROG","USDD"],["RBPF","UESH","ECBT","YBDK","CROD","PRON","URUM","STET"],["ARIS|ADUD|ASDF","AVBG|MANC|JKYL","ASLX|RIEF|CPET","ETZE|NSCH|RPDN","GOLD|SWFT|BLVL"],["OYMP|CSHL","JHTC|UNAS","SPST|SGRV","USND|JVRL","ESLX|AZST","RSSW"]);
	/*1925-26*/ loadSeason4(["RBDF","SPOR","FOLA","JESH","ULUX","RBPF","SDUD","UESH"],["ARIS","PRON","ASDF","PROG","YBDK","USDD","CROD","ECBT"],["JKYL|CPET|AVBG","URUM|RPDN|ETZE","ADUD|OYMP|ASLX","NSCH|CSHL|GOLD","STET|UNAS|MANC"],["DARE|BLVL","AZST|SPST","USND|FCOB","WALF|SWFT","JHTC"]);
	/*1926-27*/ loadSeason4(["ULUX","RBDF","SPOR","JESH","FOLA","RBPF","ARIS","PRON"],["SDUD","PROG","ASDF","USDD","YBDK","CPET","AVBG","UESH"],["NSCH|MANC","CROD|UNAS","URUM|ECBT","ADUD|ETZE","CSHL|ASLX","JKYL|RPDN","BLVL|GOLD","OYMP|DARE"],["ESLX|SWFT","USND|STET","WALF|JHTC","MINL|SPST","JWIL"]);
	/*1927-28*/ loadSeason4(["SPOR","SDUD","RBDF","RBPF","JESH","FOLA","PROG","ULUX"],["ASDF","PRON","ARIS","NSCH","CPET","USDD","MANC","YBDK"],["SWFT|ADUD","ETZE|URUM","AVBG|JKYL","ASLX|CROD","UNAS|CSHL","GOLD|STET","RPDN|UESH","OYMP|ESLX"],["USND|SPST","MINL|EGWM","MARM|JHTC","JWIL|WALF","EITZ"]);
	/*1928-29*/ loadSeason4(["SPOR","FOLA","RBDF","JESH","PRON","RBPF","ASDF","SDUD"],["ULUX","USDD","ARIS","PROG","NSCH","ADUD","CPET","SWFT"],["SPST|URUM","AVBG|UESH","ETZE|UNAS","YBDK|CROD","EGWM|STET","GOLD|ASLX","USND|JKYL","MANC|RPDN"],["OYMP","WALF","JHTC","MARM","JWIL","RSML"]);
	/*1929-30*/ loadSeason4(["FOLA","SPOR","RBDF","PRON","RBPF","ULUX","USDD","JESH"],["NSCH","SDUD","ASDF","ARIS","URUM","PROG","ADUD","SPST"],["EGWM|STET","YBDK|CPET","ETZE|SWFT","AVBG|UESH","GOLD|CROD","USND|UNAS","WALF|JKYL","OYMP|ASLX"],["RSML|BLVL","DARE|SCBT","RPDN|JHTC","JWAS|MARM","CSHL|UBSH","MANC|WGLW","MINL"]);
	/*1930-31*/ loadSeason4(["RBDF","SPOR","PRON","FOLA","ULUX","NSCH","SDUD","RBPF"],["USDD","ARIS","PROG","JESH","ASDF","URUM","STET","EGWM"],["AVBG|ADUD","CPET|BLVL","SPST|CROD","GOLD|UNAS","USND|RSML","YBDK|SWFT","WALF|JKYL","ETZE|UESH"],["SCBT|JWAS|MANC","RPDN|CGRV|CSOB","MINL|ASLX|JHTC","WGLW|DARE|UBSH","MDLB|CSHL|OYMP","MARM|TRIM"]);
	/*1931-32*/ loadSeason4(["RBDF","PRON","SPOR","ULUX","NSCH","FOLA","USDD","ARIS"],["SDUD","RBPF","PROG","JESH","ASDF","ADUD","URUM","AVBG"],["SCBT|BLVL","CPET|CROD","GOLD|SWFT","YBDK|JKYL","SPST|STET","USND|JWAS","EGWM|RSML","WALF|UNAS"],["CSOB|AREM|ETZE|CGRV","JHTC|TRIM|RPDN|DARE","UESH|MDLB|UBSH|UMRT","MANC|RBAS|MARM|VICR","CSHL|ECBT|WGLW","OYMP|ASLX|MINL"]);
	/*1932-33*/ loadSeason5(["RBDF","SPOR","PRON","FOLA","NSCH","ULUX","SDUD","RBPF"],["USDD","JESH","ARIS","ASDF","ADUD","PROG","BLVL","SCBT"],["CROD","URUM","CPET","YBDK","SWFT","AVBG","GOLD","JKYL"],["RSML|JWAS","AREM|TRIM","STET|CGRV","CSOB|ETZE","UBSH|SPST","RPDN|USND","JHTC|DARE","UESH|EGWM"],["UMRT|CSHL","ASLX|JMAM","WWMP|UNAS","VICR|RBAS","WALF|MANC","MARM|MDLB","WGLW|OYMP","MINL|ESHW"]);
	/*1933-34*/ loadSeason5(["SPOR","RBDF","USDD","ULUX","JESH","PRON","NSCH","FOLA"],["RBPF","ARIS","SDUD","ASDF","ADUD","CROD","PROG","URUM"],["CPET","AVBG","BLVL","JWAS","SWFT","RSML","YBDK","SCBT"],["TRIM|CSOB","CSHL|STET","ASLX|AREM","USND|MAMR","ETZE|JKYL","GOLD|CGRV","UBSH|RPDN","SPST|UMRT"],["DARE|RBAS|MANC","VICR|UNAS|EGWM","WWMP|BBML|RROD","MARM|MDLB|JHTC","MINL|UESH|ESHW","KOPS|LLMP|OYMP"]);
	/*1934-35*/ loadSeason5(["SPOR","RBDF","JESH","USDD","RBPF","ULUX","ARIS","PRON"],["FOLA","ASDF","NSCH","SDUD","CPET","CROD","ADUD","AVBG"],["BLVL","URUM","TRIM","PROG","CSOB","JWAS","RSML","SWFT"],["EGWM|CSHL","ASLX|STET","MANC|AREM","DARE|RBAS","YBDK|SCBT","USND|MAMR","ETZE|CGRV","GOLD|JKYL"],["MDLB|RROD|RPDN|WALF|GSWW","UESH|JHTC|UNAS|MARM|AWDG","UMRT|MDCG|BBML|JGIL|WWMP","BOUS|SPST|KOPS|MINL|TSVG","VICR|UBSH|SBRT|SCHR|SURA","BECH|OYMP|LLMP|WRMC|AHOS","ESHW|JGOB|JSCV","LAHD"]);
	/*1935-36*/ loadSeason5(["SPOR","JESH","RBDF","USDD","FOLA","ULUX","RBPF","ARIS","ASDF","NSCH"],["PRON","SDUD","CROD","CPET","AVBG","URUM","BLVL","ADUD","TRIM","PROG"],["AREM","STET","MANC","CSOB","EGWM","ASLX","RBAS","JWAS","CSHL","RSML"],["UESH|YBDK","RPDN|USND","SCBT|SPST","BBML|GOLD","RROD|CGRV","MAMR|WALF","SWFT|DARE","UNAS|MARM","MDLB|AWDG","MDCG|GSWW"],["UBSH|JGIL|ETZE","JKYL|LLMP|WRMC","DRZV|VICR|MINL","SBRT|UMRT|TSVG","KOPS|OBCN|ASTN","OYMP|FRTA|WWMP","JGOB|BECH|SCHR","ESHW|SURA","HOBS"]);
	/*1936-37*/ loadSeason5(["JESH","PRON","USDD","SDUD","RBDF","SPOR","FOLA","ULUX","RBPF","ARIS"],["ASDF","NSCH","CROD","AREM","AVBG","URUM","STET","MANC","CPET","BLVL"],["ADUD","USND","RPDN","YBDK","ASLX","UESH","PROG","CSOB","EGWM","TRIM"],["SCBT|BBML","CSHL|ETZE","RROD|GOLD","MAMR|JWAS","UBSH|JGIL","SPST|DARE","SWFT|LLMP","JKYL|WALF","RBAS|CGRV","RSML|MINL"],["MARM|RUPL|ASCH","UNAS|FRTA|DRZV","AWDG|KOPS|OYMP","SBRT|UMRT|MDLB","SCHR|VICR|JGOB","ASTN|JUNG|HOBS","TSVG|OBCN|ESHW","UWLD|MDCG"]);
	/*1937-38*/ loadSeason5(["SPOR","JESH","SDUD","USDD","PRON","ULUX","FOLA","NSCH","ASDF","RBDF"],["AVBG","CROD","ADUD","ARIS","RBPF","RPDN","STET","USND","URUM","AREM"],["YBDK","BBML","CPET","SCBT","MANC","ETZE","UESH","ASLX","BLVL","CSHL"],["RROD|JWAS","CSOB|GOLD","ASCH|TRIM","UBSH|EGWM","SWFT|DARE","PROG|LLMP","UNAS|UMRT","SPST|RUPL","MAMR|JGIL","DRZV|MARM"],["WALF|JKYL|CGRV","TSVG|KOPS|VICR","RSML|OYMP|MDLB","AWDG|ESHW|RBAS","SAND|SBRT|FRTA","OVND|JKGB|JUNG","ASTN|HRTB|UWLD","MINL|HOBS"]);
	/*1938-39*/ loadSeason5(["SDUD","USDD","SPOR","JESH","PRON","ULUX","CROD","NSCH","FOLA","AVBG"],["RBDF","ASDF","CPET","RPDN","STET","RBPF","YBDK","ADUD","ARIS","BBML"],["JWAS","RROD","SCBT","URUM","CSOB","AREM","ETZE","GOLD","MANC","USND"],["EGWM|BLVL","CGRV|ASCH","DARE|UBSH","UMRT|KOPS","ASLX|SWFT","VICR|JKYL","PROG|CSHL","UNAS|UESH","WALF|LLMP","TSVG|TRIM"],["MAMR|SPST|RUPL","SBRT|HESH|OVND","RBAS|MDCG|JGIL","ASTN|OYMP|MARM","MDLB|HOBS|MINL","RSML|JKGB|AWDG","JUNG|ESHW|FRTA","HAMM|HRTB|UWLD","SAND|DRZV"]);
	/*1939-40*/ loadSeason5(["SDUD","USDD","PRON","NSCH","SPOR","ULUX","RBDF","CROD","JESH","ASDF"],["CPET","FOLA","RROD","AVBG","RBPF","JWAS","RPDN","YBDK","STET","SCBT"],["ADUD","ARIS","URUM","AREM","EGWM","CSOB","ASCH","BBML","BLVL","CGRV"],["USND|JKYL","ETZE|UBSH","DARE|MANC","PROG|KOPS","ASLX|CSHL","RUPL|MAMR","UMRT|SWFT","OVND|HESH","VICR|SPST","GOLD|SBRT"],["JGIL|UESH|TRIM","MINL|RSML|RBAS","FRTA|OYMP|LLMP","JUNG|UNAS|JBIW","WALF|MDCG|HAMM","MARM|HOBS|MDLB","ASTN|ESHW|SAND","AWDG|JKGB|RIEF"]);
	/*1940-41*/ loadSeason5([],[],[],[],[]);
	/*1941-42*/ loadSeason5([],[],[],[],[]);
	/*1942-43*/ loadSeason5([],[],[],[],[]);
	/*1943-44*/ loadSeason5([],[],[],[],[]);
	/*1944-45*/ loadSeason5(["SDUD","SPOR","RBDF|NSCH","AVBG|JESH","USDD|PRON","SWFT"],[],[],[],[]);
	/*1945-46*/ loadSeason5(["SDUD","USDD","PRON","RBDF","SPOR","CROD","NSCH","ULUX","FOLA","CPET"],["JESH","RROD","URUM","RPDN","RBPF","ADUD","AVBG","ASDF","JWAS","ARIS"],["CSOB","STET","AREM","SCBT","YBDK","UBSH","EGWM","USND","JKYL","ETZE"],["ASCH|PROG","BLVL|ASLX","UESH|UMRT","SWFT|CGRV","RSML|BBML","TRIM|MINL","CSHL|MANC","KOPS|JGIL","MAMR|RUPL","RBAS|DARE"],["SBRT|MDLB|WALF|CLVX","UNAS|BWIT|JUNG|TSVG","SPST|HAMM|VICR|GOLD","OYMP|JBIW|MARM|OVND","JSKH|KWRM|FRTA|AWDG","HOBS|ESHW|ASTN","YBSW|MDCG|SAND"]);
	/*1946-47*/ loadSeason5(["SDUD","USDD","FOLA","ULUX","NSCH","RBDF","SPOR","PRON","JESH","RROD","CROD","CPET"],["RBPF","SCBT","STET","ADUD","URUM","CSOB","AREM","AVBG","JWAS","RPDN","ASDF","ARIS"],["CGRV|YBDK","JKYL|PROG","BLVL|BBML","ASCH|TRIG","EGWM|USND","SWFT|MANC","UBSH|RSML","UMRT|ETZE","UESH|MINL","CSHL|ASLX"],["CLVX|BWIT","MARM|MAMR","DARE|MDLB","RUPL|UNAS","JUNG|JBIW","WALF|KOPS","VICR|SPST","GOLD|RBAS","TSVG|SBRT","JGIL|HAMM"],["KWRM|FRTA|OYMP|JWIL|AWDG|ATBS","GRIV|LRNZ|JSKH|KNAP|JSCH|JUSE","RLND|ARBD|ASTN|OVND|SURA|YBSW","SAND|OBCN|HOBS|WWMP|MRTZ|PRTZ","BOUS|OYCW|KHLN|KPWW|DAHL|LARD","MUNS|SYRA|ESHW|SBEL|SURM|SRED","FCNC|HOST|MDCG|RLCN|BBEE|FOLS","JFLX|LUNA|EWLZ|JGOS|MONF","HAGN|HUPP|EVER","FELL"]);
	/*1947-48*/ loadSeason5(["SDUD","ULUX","RBDF","PRON","USDD","NSCH","FOLA","SPOR","STET","JESH","SCBT","RBPF"],["RROD","CPET","CSOB","URUM","JKYL","CROD","ADUD","CGRV","AVBG","YBDK","PROG","AREM"],["EGWM|RPDN","JWAS|RSML","UBSH|MARM","TRIG|ARIS","ASCH|USND","BWIT|SWFT","BLVL|BBML","ASDF|MANC","MAMR|CLVX","MDLB|DARE"],["UESH|ETZE","KOPS|AWDG","UNAS|WALF","JBIW|RUPL","UMRT|CSHL","KWRM|MINL","JSKH|KNAP","OYMP|FRTA","JUNG|ATBS","ASLX|JSCH"],["ESHW|JUSE|RBAS|ASTN|GOLD|WWMP","SPST|LARD|SAND|VICR|MRTZ|TSVG","HAMM|PRTZ|RLND|JGIL|SURA|GSWW","JHTC|SRED|BOUS|ARBD|DAHL|SBEL","KHLN|YBSW|GRIV|OVND|JGOS|RLCN","SNEM|SMOB|MUNS|LRNZ|FCBB|HUPP","SBRT|FOLS|FCNC|OYCW|UFLN|AHOS","HAGN|BVAT|HOST|OBCN|RHDS|HOSC","LUNA|MONF|JFLX|SURM","HOBS|EVER|SYRA|BBEE","MDCG|FELL"]);
	/*1948-49*/ loadSeason5(["SPOR","FOLA","SDUD","NSCH","PRON","RBDF","ULUX","USDD","STET","CSOB","RROD","CPET"],["JESH","URUM","CGRV","RSML","SCBT","JKYL","CROD","RBPF","ADUD","JWAS","EGWM","RPDN"],["AVBG|PROG","YBDK|BLVL","ARIS|AREM","USND|UBSH","TRIG|ASCH","MARM|UNAS","BBML|BWIT","ETZE|UESH","WALF|KOPS","AWDG|SWFT"],["ASDF|MINL|UMRT","MDLB|ASTN|KWRM","RBAS|JSCH|DARE","MAMR|TSVG|VICR","SPST|CLVX|MANC","CSHL|WWMP|JBIW","ASLX|GOLD|RUPL","OYMP|MRTZ|SAND","JSKH|ATBS|FRTA","ESHW|KNAP|JUNG"],["LRNZ|SURA|LUNA|ARBD|SMOB|RLCN","MUNS|DONC|SNEM|OBCN|LARD|HUPP","SYRA|JGOS|HAMM|BBEE|BSSW|SBEL","GRIV|RHDS|TLMD|OYCW|SRED|AHOS","HOST|HARL|KHLN|OVND|PRTZ|HOSC","JFLX|TWTC|JHTC|REIS|EVER","FCNC|DAHL|SBRT|JGIL|JUSE","GRAU|MDCG|BWMD|UFLN","HAGN|SURM|MONF","HOBS|BAST|BVAT"]);
	/*1949-50*/ loadSeason5(["SDUD","NSCH","SPOR","RBDF","ULUX","JESH","USDD","PRON","STET","FOLA","URUM","CGRV"],["RROD","CROD","YBDK","CPET","RSML","CSOB","AVBG","RBPF","PROG","BLVL","SCBT","JKYL"],["EGWM|ADUD","RPDN|JWAS","MARM|ASDF","USND|UBSH","DARE|AREM","ARIS|RBAS","ASTN|MAMR","BBML|MDLB","BWIT|ASCH","MINL|UNAS","TRIG|KWRM","JSCH|UMRT"],["JBIW|ETZE|UESH","RUPL|WWMP|LUNA","SAND|TSVG|SWFT","WALF|AWDG|CSHL","KOPS|CLVX|SNEM","LRNZ|MRTZ|SPST","ARBD|GOLD|MANC","VICR|RLCN|OYMP","ASLX|BBEE|SMOB","MUNS"],["LARD|SURA|HAMM|OVND|TLMD|FRTA","ATBS|HARL|SYRA|REIS|JHTC|OYCW","BSSW|DONC|SBRT|AHOS|KHLN|OBCN","PRTZ|UFLN|USMM|JGIL|JSKH|JUNG","JUSE|HUPP|FCNC|HOSC|MDCG|BWMD","SRED|DAHL|BOUS|BAST|HOBS|GRAU","EVER|RHDS|JFLX|SURM|HAGN|HOST","JOSP|JGOS|JHSD","BVAT","MONF"]);
	/*1950-51*/ loadSeason5(["JESH","NSCH","RBDF","SDUD","SPOR","STET","ULUX","PRON","RROD","CROD","USDD","YBDK"],["FOLA","AVBG","URUM","RSML","JWAS","RPDN","CGRV","ADUD","CSOB","CPET","EGWM","RBPF"],["ASDF|ARIS","BLVL|BBML","SCBT|PROG","ASCH|ETZE","JKYL|USND","MAMR|DARE","UESH|ASTN","AREM|BWIT","UBSH|MARM","RBAS|WWMP","LUNA|JBIW","MDLB|RUPL"],["TLMD|WALF|OVND","UNAS|ARBD|JSCH","HAMM|MINL|AWDG","CSHL|KWRM|CLVX","SWFT|KOPS|TSVG","SNEM|SAND|LARD","SPST|LRNZ|GOLD","OYMP|UMRT|MRTZ","MANC|ASLX|HARL","TRIG|FRTA|RLCN"],["ATBS|HTC|USMM|KNAP|VICR","BVAT|AGN|JFLX|AHOS|JGIL","SRED|DCG|SYRA|HUPP|OYCW","JOSP|SKH|FCNC|DAHL|REIS","BSSW|HLN|JUNG|RHDS|BWMD","EVER|BRT|HOST|JGOS|OBCN","PRTZ|SHW|BOUS|TWTC|BAST","SMOB|HSD|GRAU|BBEE","JUSE|OBS|BDBB|UFLN","MONF|UNS|HOSC"]);
	/*1951-52*/ loadSeason5(["NSCH","SPOR","SDUD","PRON","FOLA","RBDF","JESH","ULUX","STET","RROD"],["RSML|ADUD","CGRV|URUM","YBDK|USDD","PROG|BLVL","JWAS|CROD","AVBG|ASCH","ARIS|CPET","RBPF|CSOB","RPDN|ASDF","BBML|SCBT"],["JKYL|ETZE","TLMD|DARE","RBAS|WALF","UESH|ASTN","UBSH|USND","MAMR|RUPL","AREM|MARM","LUNA|JBIW","BWIT|OVND","MDLB|WWMP"],["CSHL|MINL|AWDG","SWFT|SAND|JSCH","UNAS|HAMM|BVAT","SNEM|KOPS|GOLD","JHTC|KWRM|TSVG","SPST|VICR|JGIL","HAGN|UMRT|LARD","OYMP|ARBD|MRTZ","MDCG|LRNZ|CLVX"],["SRED|EGWM|SYRA|FRTA|HUPP","ATBS|JSKH|JUNG|BWMD|RHDS","BSSW|MANC|BDBB|OBCN|AHOS","JOSP|TRIG|HOST|OYCW|DAHL","PRTZ|ASLX|USMM|REIS|TWTC","EVER|SBRT|FCNC|BAST|HARL","JHSD|BOUS|UFLN","KHLN|MUNS|","HOBS"]);
	/*1952-53*/ loadSeason5(["PRON","JESH","SDUD","RBDF","FOLA","ULUX","RSML","NSCH","SPOR","STET","ADUD","RROD"],["CGRV|USDD","RBPF|URUM","PROG|BLVL","WALF|CPET","YBDK|CSOB","AVBG|CROD","JWAS|ASCH","BBML|TLMD","ARIS|JKYL","ETZE|ASDF","RPDN|SCBT","DARE|UESH"],["KOPS|CSHL","MINL|HAMM","MARM|MAMR","ASTN|UNAS","AWDG|RBAS","OVND|SAND","USND|AREM","JBIW|SWFT","RUPL|LUNA","GOLD|BWIT","JSCH|MDLB","BVAT|UBSH"],["SNEM|ARBD","EGWM|BWMD","JHTC|SRED","JSKH|VICR","MDCG|ATBS","OYMP|WWMP","SPST|TSVG","UMRT|JUNG","KWRM|LARD","LRNZ|JGIL","SYRA|RHDS","HAGN"],["OYCW|TRIG","PRTZ|SBRT","BSSW|MANC","OBCN|JHSD","REIS|ASLX","FRTA|USMM","BAST|BDBB","TWTC|MUNS","JOSP|KHLN","CLVX|BOUS","AHOS|HOST","UFLN|FCNC"]);
	/*1953-54*/ loadSeason5(["JESH","FOLA","PRON","CGRV","ULUX","SDUD","NSCH","STET","RBDF","RSML","USDD","SPOR"],["RROD|ADUD","PROG|BLVL","JWAS|CROD","RBPF|URUM","BBML|CSOB","AVBG|ASCH","ETZE|HAMM","ARIS|TLMD","WALF|CPET","YBDK|ASDF","KOPS|JKYL","MINL|CSHL"],["RPDN|SCBT","DARE|MAMR","ASTN|EGWM","USND|UNAS","OVND|RBAS","MARM|SAND","GOLD|AREM","ARBD|SWFT","AWDG|LUNA","BWMD|SNEM","RUPL|UESH","JBIW|BWIT"],["JHTC|JSCH","UMRT|MANC","KWRM|PRTZ","JSKH|SRED","SBRT|BVAT","UBSH|VICR","LRNZ|TSVG","SPST|JUNG","MDCG|BSSW","TRIG|OYCW","OYMP|LARD","MDLB"],["CLVX|JHSD","JUSE|HOST","FRTA|ASLX","OBCN|HOBS","JOSP|BDBB","BAST|KHLN","UFLN|SYRA","AHOS|USMM","JGIL|MUNS","REIS|HAGN"]);
	/*1954-55*/ loadSeason5(["SDUD","FOLA","ULUX","NSCH","PRON","RSML","RBDF","ADUD","JESH","RROD","CGRV","STET"],["SPOR|CROD","PROG|URUM","ARIS|BLVL","JWAS|USDD","WALF|ASCH","ETZE|SCBT","RBPF|HAMM","RPDN|CPET","BBML|CSOB","AVBG|TLMD","YBDK|ASDF","DARE|MAMR"],["KOPS|AREM","MINL|RBAS","AWDG|UMRT","ARBD|JKYL","USND|SNEM","MANC|EGWM","OVND|UNAS","BWMD|SAND","JSCH|SWFT","MARM|JHTC","ASTN|CSHL","GOLD|LUNA"],["CLVX|UBSH","TSVG|KWRM","BVAT|SBRT","VICR|BWIT","BSSW|LRNZ","JBIW|TRIG","FRTA|UESH","SRED|JSKH","JUSE|MDCG","JUNG|SPST","RUPL|HOST","PRTZ|JHSD"],["MDLB|JOSP","OYMP|BAST","KHLN|OBCN","MLSV|JGIL","BDBB|OYCW","HAGN|REIS","SYRA|LARD","ASLX|UFLN","MUNS|ATBS","HOBS|TWTC","ISKA|AHOS","USMM"]);
	/*1955-56*/ loadSeason5(["SPOR","SDUD","PRON","ADUD","JESH","FOLA","NSCH","RBDF","ULUX","RSML","RROD","CROD"],["CGRV|STET","ARIS|USDD","JWAS|BLVL","PROG|AREM","WALF|URUM","RPDN|HAMM","AVBG|TLMD","BBML|SCBT","RBPF|ASCH","ETZE|CPET","MINL|CSOB","KOPS|RBAS"],["YBDK|UBSH","OVND|KWRM","TSVG|UNAS","USND|EGWM","DARE|JKYL","AWDG|UMRT","CLVX|ASDF","MANC|SAND","BWMD|MAMR","MARM|SWFT","ARBD|JHTC","JSCH|SNEM"],["JUSE|CSHL","BVAT|SBRT","JBIW|UESH","VICR|MDLB","ASTN|LUNA","SRED|JSKH","JUNG|LRNZ","GOLD|TRIG","BSSW|OYMP","BAST|SPST","JOSP|BWIT","FRTA|MDCG"],["MLSV|RUPL","SYRA|PRTZ","HOBS|BDBB","HOST|OYCW","HAGN|RHDS","MUNS|OBCN","KHLN|UFLN","ASLX|LARD","USMM|ATBS","YBWT|REIS","ISKA|TWTC","ESHW|JGIL","JHSD"]);
	/*1956-57*/ loadSeason5(["SDUD","JESH","RBDF","CGRV","SPOR","ULUX","ADUD","PRON","STET","FOLA","NSCH","RSML"],["CROD|USDD","ARIS|BLVL","RPDN|URUM","YBDK|RROD","WALF|ASCH","JWAS|HAMM","ETZE|AREM","PROG|CPET","AVBG|TLMD","RBPF|UBSH","BBML|SCBT","OVND|KWRM"],["DARE|CSOB","CLVX|JKYL","USND|UNAS","TSVG|SWFT","AWDG|CSHL","JUSE|EGWM","KOPS|ASDF","BVAT|MAMR","MANC|RBAS","MINL|UMRT","MARM|SAND","BWMD|SBRT"],["ASTN|SPST","SRED|LUNA","VICR|LRNZ","RUPL|TRIG","HOBS|UESH","GOLD|SNEM","JBIW|JHTC","ARBD|MDLB","PRTZ|MLSV","JSCH|OYMP","JUNG|JSKH","BSSW|SYRA"],["OYCW|MDCG|UFLN","OBCN|BWIT|LARD","BDBB|HOST|RHDS","HAGN|USMM|BGHP","ISKA|MUNS|JGIL","KHLN|ASLX|AHOS","ATBS|YBWT|TWTC","REIS|ESHW|BAST","FRTA|JHSD"]);
	/*1957-58*/ loadSeason5(["JESH","RBDF","SDUD","STET","SPOR","CROD","ULUX","PRON","CGRV","ADUD","USDD","FOLA"],["NSCH","JWAS","YBDK","BLVL","WALF","ARIS","RROD","ASCH","RPDN","HAMM","RSML","URUM"],["CLVX","RBPF","CSOB","JKYL","ETZE","DARE","AREM","TLMD","PROG","CPET","UBSH","AVBG"],["KWRM|SPST","OVND|SCBT","AWDG|ASDF","USND|LUNA","SRED|SWFT","JUSE|CSHL","TSVG|UNAS","BVAT|MANC","KOPS|RBAS","ASTN|BBML","UMRT|MAMR","MINL|EGWM"],["VICR|TRIG|JHTC|GOLD","ARBD|SAND|MLSV|RHDS","JBIW|LRNZ|SNEM|AHOS","BWMD|SBRT|JSKH|JSCH","RUPL|MDLB|BSSW|BGHP","SYRA|BWIT|UESH|PRTZ","OYCW|HOST|HOBS|ATBS","JUNG|MUNS|OYMP|UFLN","MARM|KHLN|MDCG|LARD","FRTA|JCNC|ESHW|JGIL","REIS|USMM|HAGN|TWTC","BDBB|ASLX|CLMC|BAST","OBCN|YBWT|ISKA"]);
	/*1958-59*/ loadSeason5(["JESH","RBDF","SPOR","SDUD","ADUD","PRON","ULUX","CGRV","STET","NSCH","JWAS","CROD"],["FOLA","ARIS","USDD","WALF","BLVL","ASCH","RPDN","HAMM","YBDK","RROD","CLVX","RBPF"],["CSOB","URUM","DARE","JKYL","RSML","CPET","AREM","ETZE","KWRM","TLMD","PROG","SPST"],["AVBG|USND","TRIG|OVND","SCBT|KOPS","BBML|BVAT","UNAS|AWDG","ASDF|JUSE","JHTC|SRED","CSHL|TSVG","RBAS|ARBD","SWFT|GOLD","UBSH|VICR","MANC|ASTN"],["RHDS|UMRT|KHLN|UESH","JSCH|RUPL|MDLB|OYMP","ATBS|LRNZ|EGWM|JSKH","PRTZ|MARM|SBRT|HOBS","AHOS|JUNG|SAND|SNEM","UFLN|BWMD|BWIT|MAMR","LARD|MINL|YBWT|MLSV","BGHP|JBIW|HOST|BSSW","JGIL|REIS|MUNS|ISKA","BGNV|OYCW|USMM|CLMC","BAST|BDBB|ASLX|MDCG","TWTC|OBCN|JCNC|ESHW","FRTA|SYRA"]);
	/*1959-60*/ loadSeason5(["JESH","SDUD","CGRV","ULUX","NSCH","ADUD","RBDF","ARIS","SPOR","STET","FOLA","PRON"],["CROD","URUM","BLVL","JWAS","CSOB","USDD","WALF","YBDK","RROD","ASCH","RPDN","HAMM"],["AVBG","ETZE","CPET","DARE","AREM","RBPF","JKYL","USND","KWRM","CLVX","RSML","TLMD"],["SPST|JHTC","BVAT|SWFT","UNAS|TRIG","CSHL|BBML","OVND|MDLB","JUSE|RBAS","SRED|ASDF","KHLN|UESH","TSVG|SCBT","AWDG|KOPS","GOLD|PROG","ARBD|UMRT"],["SBRT|EGWM|RUPL|RHDS","MAMR|SAND|MINL|JSCH","UBSH|LRNZ|MARM|PRTZ","MLSV|MANC|JBIW|ATBS","OYMP|YBWT|BWMD|UFLN","BSSW|BWIT|VICR|LARD","HOBS|HOST|OYCW|BGNV","ISKA|USMM|JUNG|AHOS","MDCG|ASLX|OBCN|TWTC","CLMC|ASTN|REIS|BGHP","SNEM|MUNS|BDBB|FOLS","JSKH|JCNC|JGIL|BAST","ESHW|SYRA|FRTA"]);
	/*1960-61*/ loadSeason5(["SPOR","JESH","ULUX","RBDF","SDUD","CGRV","FOLA","NSCH","URUM","ARIS","CROD","STET"],["ADUD","USDD","PRON","JWAS","AVBG","ASCH","CSOB","BLVL","RROD","YBDK","WALF","ETZE"],["CPET","JHTC","DARE","RBPF","RPDN","JKYL","SPST","AREM","USND","KWRM","CLVX","HAMM"],["BVAT|MDLB","BBML|EGWM","RSML|ASDF","SBRT|RBAS","TRIG|TLMD","AWDG|SCBT","OVND|CSHL","TSVG|SWFT","JUSE|UNAS","SRED|KHLN","RUPL|UESH","RHDS|KOPS"],["UBSH|SAND|MARM|VICR|GOLD","SNEM|MANC|HOBS|UMRT|PRTZ","YBWT|LRNZ|OYMP|BWMD|BGNV","BWIT|HOST|MAMR|OBCN|BGHP","CLMC|MUNS|JSCH|ARBD|LARD","MLSV|USMM|MINL|JBIW|BAST","MDCG|JUNG|JSKH|OYCW|UFLN","PROG|ASTN|BSSW|BDBB|FOLS","ASLX|SYRA|ATBS|REIS|AHOS","ESHW|JCNC|ISKA|JGIL|TWTC","EHLR|BYUD|BRCH"]);
	/*1961-62*/ loadSeason5(["ULUX","ADUD","SPOR","NSCH","JESH","ARIS","SDUD","RBDF","USDD","FOLA","CGRV","URUM"],["AVBG","BLVL","JWAS","PRON","CPET","CROD","YBDK","STET","CSOB","RROD","ASCH","JHTC"],["RPDN","MDLB","JKYL","WALF","RBPF","ETZE","USND","KWRM","DARE","SPST","AREM","BVAT"],["MARM|RSML","EGWM|TRIG","AWDG|TLMD","TSVG|BBML","OVND|UNAS","JUSE|SCBT","CLVX|ASDF","VICR|SBRT","KHLN|SWFT","CSHL|RBAS","SRED|UBSH","GOLD|HAMM"],["LRNZ|BGNV|HOBS|SNEM","REIS|JSCH|HOST|MAMR","BWMD|PRTZ|MANC|SAND","OBCN|UFLN|JBIW|YBWT","UMRT|JGIL|KOPS|USMM","ARBD|BGHP|OYMP|UESH","BRCH|RHDS|JSKH|BWIT","ATBS|FOLS|JCNC|CLMC","MINL|LARD|ASTN|EHLR","JUNG|MRTZ|BYUD|JHAG","OYCW|TWTC|MUNS|ESHW","SYRA|BAST|ASLX|MDCG","RUPL|AHOS|PROG","BDBB"]);
	/*1962-63*/ loadSeason5(["JESH","ULUX","RBDF","ARIS","ADUD","SPOR","NSCH","SDUD","USDD","AVBG","FOLA","BLVL"],["JWAS","PRON","CGRV","URUM","YBDK","MDLB","CSOB","CPET","CROD","RPDN","STET","RROD"],["RSML","MARM","ETZE","ASCH","RBPF","DARE","WALF","JKYL","SPST","USND","KWRM","JHTC"],["TSVG|TLMD","LRNZ|AREM","AWDG|EGWM","OVND|ASDF","UNAS|SNEM","BBML|TRIG","BVAT|RBAS","HOBS|SWFT","CLVX|SCBT","VICR|CSHL","JUSE|SBRT","BGNV|KHLN"],["SRED|MANC|JBIW|SAND","JGIL|MAMR|OYCW|USMM","JSCH|OYMP|ARBD|YBWT","FOLS|BRCH|HOST|UESH","LARD|PROG|REIS|JCNC","GOLD|KOPS|OBCN|CLMC","UFLN|MINL|BWMD|BWIT","TWTC|ASLX|UMRT|UBSH","PRTZ|HAMM|JUNG|MLSV","MRTZ|ISKA|RUPL|EHLR","BGHP|JSKH|MUNS|MDCG","KPWW|ATBS|BYUD|NORZ","BAST|ASTN|SYRA|ESHW","RHDS|JHAG|BDBB"]);
	/*1963-64*/ loadSeason5(["ARIS","ULUX","SDUD","RBDF","JESH","SPOR","JWAS","ADUD","USDD","NSCH","PRON","AVBG"],["URUM","RPDN","CSOB","YBDK","FOLA","MDLB","CPET","BLVL","CGRV","RSML","CROD","MARM"],["ETZE","TSVG","STET","RBPF","TLMD","JKYL","RROD","ASCH","WALF","SPST","DARE","USND"],["EGWM|ASDF","TRIG|SCBT","SRED|CSHL","MANC|KWRM","JBIW|SNEM","LRNZ|UNAS","OVND|AREM","AWDG|BBML","CLVX|JHTC","BVAT|SAND","HOBS|RBAS","VICR|SWFT"],["JSCH|UMRT|PROG|UESH","GOLD|MINL|KOPS|USMM","LARD|OBCN|OYMP|SBRT","FOLS|OYCW|MAMR|YBWT","JGIL|REIS|BRCH|CLMC","BGNV|HOST|RUPL|UBSH","UFLN|KHLN|JSKH|MLSV","BGHP|JUNG|JUSE|BWIT","MRTZ|BWMD|ISKA|MDCG","PRTZ|MUNS|ASLX|JCNC","KPWW|SYRA|ATBS|NORZ","HARL|ARBD|HAMM|EHLR","TWTC|BYUD|ASTN|JHAG","BAST|BDBB"]);
	/*1964-65*/ loadSeason6(["SDUD","ULUX","JESH","ARIS","SPOR","ADUD","RBDF","JWAS","URUM","USDD","RPDN","NSCH"],["CPET","AVBG","PRON","FOLA","MDLB","RSML","TSVG","CGRV","ETZE","YBDK","CSOB","BLVL"],["CROD","STET","RROD","ASDF","ASCH","EGWM","RBPF","MARM","JKYL","WALF","SPST","TRIG","TLMD","SCBT"],["CSHL|KWRM","CLVX|UNAS","DARE|UMRT","AWDG|AREM","OVND|UESH","PROG|JHTC","SRED|SNEM","JSCH|SAND","BVAT|RBAS","LRNZ|MANC","USND|BBML","JBIW|HOBS"],["OBCN|KOPS","MINL|UBSH","BRCH|MLSV","OYCW|MAMR","RUPL|SWFT","GOLD|USMM","REIS|SBRT","VICR|CLMC","LARD|HOST","FOLS|OYMP","JGIL|YBWT","BGNV|JSKH"],["JUNG|JUSE|EHLR","ATBS|MRTZ|ISKA","BWMD|KPWW|BWIT","SYRA|HARL|KHLN","MUNS|PRTZ|ASLX","ARBD|BGHP|HAMM","BYUD|UFLN|ESHW","BDBB|BAST|MDCG","JCNC|TWTC|ASTN","BOUS|SBCK|NORZ","FRTA"]);
	/*1965-66*/ loadSeason6(["ARIS","ULUX","USDD","URUM","JESH","AVBG","SPOR","SDUD","CPET","JWAS","RBDF","ADUD"],["MDLB","RPDN","CGRV","YBDK","PRON","NSCH","FOLA","CROD","TSVG","STET","ETZE","RSML"],["CSOB","EGWM","CSHL","RROD","WALF","UNAS","KWRM","RBPF","MARM","JKYL","CLVX","BLVL","ASDF","ASCH"],["DARE|SCBT","SPST|TLMD","SRED|PROG","UMRT|AREM","AWDG|JHTC","OVND|UESH","JSCH|KOPS","BVAT|TRIG","MINL|UBSH","LRNZ|SNEM","OBCN|RBAS","MANC|SAND"],["VICR|OYMP","JUNG|MLSV","JUSE|HOST","BRCH|SWFT","LARD|EHLR","REIS|HOBS","USND|BBML","OYCW|ISKA","GOLD|MAMR","JBIW|SBRT","RUPL|CLMC","FOLS|USMM"],["KPWW|ARBD|ATBS","MRTZ|BWMD|BWIT","HARL|YBWT|MDCG","BGNV|AFLX|HAMM","JGIL|JCNC|ASLX","BGHP|BYUD|KHLN","UFLN|BDBB|ASTN","PRTZ|MUNS|SBCK","BAST|BOUS|JSKH","TWTC|SYRA|NORZ","ESHW"]);
	/*1966-67*/ loadSeason6(["JESH","SPOR","ULUX","ARIS","USDD","MDLB","URUM","AVBG","CPET","SDUD","JWAS","RPDN"],["PRON","RBDF","ADUD","FOLA","CSOB","STET","EGWM","CGRV","NSCH","YBDK","CROD","TSVG"],["CSHL","KWRM","RROD","UNAS","RSML","ETZE","SCBT","DARE","TLMD","WALF","MARM","SPST","RBPF","JKYL"],["AWDG|BLVL","JSCH|ASCH","OVND|ASDF","VICR|SNEM","JUNG|UESH","LRNZ|UBSH","BVAT|JHTC","UMRT|OYMP","SRED|MLSV","CLVX|TRIG","MINL|AREM","KOPS|PROG"],["ARBD|SBRT","JBIW|SWFT","KPWW|BWIT","USND|MAMR","REIS|BBML","OBCN|MANC","LARD|EHLR","ATBS|HOST","GOLD|HOBS","JUSE|RBAS","OYCW|SAND","BRCH|ISKA"],["MRTZ|AFLX|YBWT","TWTC|JSKH|USMM","HARL|RUPL|MDCG","BGHP|BWMD|BOUS","BGNV|SYRA|CLMC","MGWW|BYUD|HAMM","PRTZ|BDBB|NORZ","UFLN|JCNC|ESHW","JGIL|SBCK|KHLN","FRTA|ASTN|LUNA","BAST|MUNS|ASLX","FOLS"]);
	/*1967-68*/ loadSeason6(["JESH","URUM","ULUX","ARIS","USDD","SPOR","AVBG","RBDF","MDLB","PRON","SDUD","CPET"],["FOLA","CGRV","RPDN","NSCH","CSOB","EGWM","CSHL","ADUD","JWAS","STET","YBDK","KWRM"],["RROD","ETZE","RSML","DARE","BLVL","CROD","JSCH","SCBT","WALF","ASCH","TSVG","AWDG","TLMD","UNAS"],["JBIW|RBPF","MARM|SWFT","VICR|ASDF","OVND|UESH","SRED|JKYL","SPST|SNEM","ARBD|SBRT","JUNG|MLSV","LRNZ|JHTC","UMRT|OYMP","BVAT|TRIG","CLVX|UBSH"],["REIS|MAMR","HOBS|YBWT","GOLD|MANC","ATBS|AFLX","KPWW|USMM","MINL|AREM","LARD|RBAS","USND|HOST","JUSE|BBML","MRTZ|BWIT","KOPS|EHLR","OBCN|PROG"],["PRTZ|SAND|BRCH","TWTC|MDCG|BDBB","MGWW|HAMM|OYCW","BGHP|JSKH|JCNC","JGIL|BOUS|BWMD","SBCK|CLMC|MUNS","HARL|VINE|BYUD","UFLN|KHLN|ISKA","FOLS|NORZ|SYRA","BAST|ESHW|ASTN","BGNV|LUNA|RUPL","FRTA|ASLX"]);
	/*1698-69*/ loadSeason6(["AVBG","JESH","ARIS","ULUX","USDD","RBDF","SPOR","MDLB","URUM","PRON","CGRV","FOLA"],["SDUD","STET","JWAS","ETZE","ADUD","NSCH","CSHL","CSOB","EGWM","CPET","RROD","RPDN"],["RBPF","RSML","DARE","JSCH","CROD","BLVL","KWRM","SCBT","YBDK","MARM","SWFT","ASCH","JBIW","WALF"],["OVND|UESH","AWDG|ASDF","HOBS|MAMR","JUNG|TLMD","VICR|MLSV","SPST|JHTC","TSVG|SNEM","REIS|UNAS","OYMP|YBWT","ARBD|JKYL","SRED|SBRT","LRNZ|UMRT"],["USND|SAND","GOLD|AREM","BRCH|MANC","KPWW|TRIG","BVAT|BBML","MINL|USMM","MRTZ|HOST","ATBS|AFLX","LARD|UBSH","JUSE|BWIT","CLVX|RBAS","PRTZ|BDBB"],["MGWW|KOPS|ASLX|CLMC","BGHP|OBCN|BOUS|MDCG","HARL|OYCW|SYRA|JSKH","UFLN|BWMD|HAMM|NORZ","TWTC|ASTN|VINE|LUNA","BGNV|RUPL|BYUD|ESHW","BAST|ASCB|JCNC|KHLN","FOLS|JGIL|LADH|SBCK","AHOS|ALCR|MUNS|EHLR","RAMB|FRTA|PROG|ISKA"]);
	/*1969-70*/ loadSeason6(["JESH","URUM","SPOR","RBDF","ULUX","ARIS","AVBG","STET","SDUD","PRON","USDD","MDLB"],["CGRV","ADUD","FOLA","ETZE","NSCH","JWAS","RSML","EGWM","CPET","CSHL","RBPF","CSOB"],["SCBT","AWDG","JSCH","DARE","CROD","ASDF","BLVL","OVND","YBDK","RROD","KWRM","UESH","RPDN","MARM"],["USND|JHTC","VICR|SWFT","SPST|SNEM","GOLD|JBIW","OYMP|MLSV","HOBS|SAND","WALF|JKYL","MAMR|AREM","ARBD|TLMD","TSVG|UNAS","REIS|ASCH","JUNG|YBWT"],["KOPS|UBSH","KPWW|BBML","SRED|MANC","BVAT|HOST","LRNZ|BWIT","MGWW|UMRT","MINL|CLMC","LARD|TRIG","ATBS|SBRT","MRTZ|ASLX","BRCH|AFLX","JUSE|USMM"],["UFLN|BOUS|JSKH|BWMD","PRTZ|RBAS|MDCG|BDBB","BGHP|SYRA|NORZ|RUPL","CLVX|HAMM|LUNA|OYCW","BGNV|JCNC|ESHW|OBCN","HARL|PROG|ISKA|ASCB","TWTC|VINE|SBCK|ALCR","AHOS|BYUD|ASTN|JGIL","RAMB|LADH|EHLR|BAST","FOLS|MUNS|KHLN"]);
	/*1970-71*/ loadSeason6(["ULUX","ARIS","JESH","AVBG","SPOR","RBDF","URUM","ADUD","PRON","STET","SDUD","CGRV"],["NSCH","ETZE","CSHL","RSMB","FOLA","JWAS","SCBT","CPET","AWDG","USDD","MDLB","EGWM"],["CROD","JHTC","RBPF","OVND","BLVL","CSOB","VICR","ASDF","SWFT","YBDK","JSCH","RROD","DARE","USND"],["WALF|MAMR","BBML|KWRM","SPST|SAND","RPDN|AREM","GOLD|MLSV","KOPS|JBIW","KPWW|UESH","HOBS|SNEM","OYMP|JKYL","TSVG|TLMD","MARM|UBSH","ARBD|UNAS"],["BWMD|HOST","LRNZ|MANC","JUNG|TRIG","MRTZ|YBWT","REIS|BOUS","MGWW|JSKH","SRED|BWIT","BVAT|ASCH","MINL|CLMC","UFLN|ASLX","LARD|SBRT","ATBS|UMRT"],["PRTZ|JUSE|RBAS|MDCG","BGHP|BDBB|JCNC|LUNA","CLVX|RUPL|AFLX|HAMM","FOLS|OBCN|LADH|ESHW","AHOS|OYCW|SYRA|KHLN","HARL|BRCH|USMM|ISKA","RAMB|ALCR|MUNS|NORZ","TWTC|ASCB|ASTN|EHLR","BGNV|BAST|VINE|PROG","CBSH|JGIL|BYUD|SBCK"]);
	/*1971-72*/ loadSeason6(["ARIS","URUM","RBDF","JESH","AVBG","ETZE","SPOR","NSCH","STET","ULUX","PRON","ADUD"],["SCBT","FOLA","CGRV","CROD","SDUD","JTHC","RSMB","CSHL","USDD","JWAS","CPET","AWDG"],["MDLB","EGWM","BLVL","RBPF","VICR","BBML","KWRM","OVND","CSOB","SWFT","ASDF","YBDK","WALF","MAMR"],["SPST|HOST","DARE|SAND","OYMP|RROD","JSCH|MANC","LRNZ|UESH","BWMD|SNEM","HOBS|AREM","RPDN|MLSV","JUNG|JKYL","WLTZ|TLMD","KPWW|JBIW","TSVG|KOPS"],["SRED|JSKH","REIS|BOUS","MARM|RBAS","ARBD|UBSH","MRTZ|YBWT","BDBB|UNAS","MINL|CLMC","BVAT|BWIT","UFLN|ASCH","PRTZ|TRIG","MGWW|ASLX","JUSE|MDCG"],["BGHP|AFLX|LUNA","AHOS|HAMM|SBRT","CLVX|ASTN|JCNC","LARD|OYCW|LADH","SBCK|BRCH|ESHW","SELL|ATBS|MUNS","RAMB|RUPL|VINE","FOLS|OBCN|KHLN","JGIL|ISKA|USMM","BAST|ALCR|BYUD","TWTC|ASCB|NORZ","HARL|UMRT|SYRA","CBSH|PROG|EHLR"]);
	/*1972-73*/ loadSeason6(["JESH","ULUX","RBDF","FOLA","ETZE","URUM","ARIS","AVBG","SPOR","NSCH","STET","SCBT"],["RSMB","SDUD","PRON","CROD","MDLB","JWAS","CGRV","JHTC","ADUD","USDD","CSHL","EGWM"],["RBPF","CPET","OVND","CSOB","VICR","KWRM","DARE","BBML","HOST","SAND","BLVL","SWFT","SPST","AWDG"],["WLTZ|RPDN","HOBS|ASDF","JSCH|RROD","JSKH|MAMR","JUNG|MLSV","BWMD|BOUS","YBDK|SNEM","OYMP|JKYL","LRNZ|MANC","REIS|TLMD","WALF|UESH","SRED|AREM"],["ARBD|AFLX","MRTZ|YBWT","MARM|RBAS","BGHP|HAMM","KPWW|CLMC","JBIW|TRIG","BDBB|KOPS","UFLN|UNAS","TSVG|LUNA","MINL|ASCH","PRTZ|UBSH","BVAT|BWIT"],["BRCH|CLVX|SYRA|SBRT","ERPL|LARD|LADH|ASTN","ASCB|AHOS|OYCW|MDCG","ATBS|MGWW|UMRT|EHLR","SELL|RAMB|USMM|ISKA","RUPL|TWTC|OBCN|ESHW","JUSE|FOLS|MUNS|ASLX","SBCK|HARL|JCNC|PROG","JGIL|CBSH|VINE|KHLN","ALCR|UEDF|BYUD|NORZ","BAST"]);

	/*2024-25*/ loadSeason5(["DIFF","UNAS","F91D","RACE","PRON","SWFT","MDLB","JESH","UNTP","HOST","VICR","RODG","WLTZ","SCBT","FOLA","MDCG"],["MAMR","KAER","ATBS","JCNC","LUXC","MARM","WALF","ETZE","BDBB","ASTN","URUM","UFLN","SCHF","KOEP","AVBG","SAND"],["LRNZ|BLVL","MRTZ|SYRA","JSCH|SHGN","BWMD|CGRV","YBDK|YBWT","JUSE|DARE","KHLN|UNRB","KOSM|SNEM","BAST|JUNG","JGIL|BWIT","AHOS|MUNS","NORD|RSMB","ERPL|RBPF","AAHE|EHLR","STNG|U5KT","OVND|USBC"],["MINL|KOPS","RPLL|CSOB","GBHT|SBRT","WINC|UNMW","RHSE|JBIW","TSVG|TRIG","FOLS|USMM","FCPR|ASLX","RAMB|CLMC","OYCW|LADH","BVAT|MLSV","SELL|ESHW","REIS|NORZ","ASCB|LUNA"],["CBSH","UESH","RBAS","BIEK","CLVX","BRCH","LARD","EXGV","KPWW"]);
	
	positionHeight = 5;

	t1d = "M45,69";
	t2d = "M105,69";
	t3d = "M105,69";
	t4d = "M155,69";
	t5d = "M275,69";
	t6d = "M595,69";
	leagueSizes.forEach(s=>{

		one = s[0];
		two = s.length >= 2 ? one + s[1] : null;
		three = s.length >= 3 ? two + s[2] : null;
		four = s.length >= 4 ? (three + s[3]) : null;
		five = s.length >= 5 ? (four + s[4]) : null;
		six = s.length >= 6 ? (five + s[5]) : null;

		onePos = one*positionHeight
		t1d += "v" + onePos + "h10v-" + onePos + "h-10h10";

		if ( two !== null ) {
			twoPos = two*positionHeight;
			t2d += "v" + twoPos + "h10v-" + twoPos + "h-10h10";
		}

		if ( three !== null ) {
			threePos = three*positionHeight;
			t3d += "v" + threePos + "h10v-" + threePos + "h-10h10";
		}

		if ( four !== null ) {
			fourPos = four*positionHeight;
			t4d += "v" + fourPos + "h10v-" + fourPos + "h-10h10";
		}

		if ( five !== null ) {
			fivePos = five*positionHeight;
			t5d += "v" + fivePos + "h10v-" + fivePos + "h-10h10";
		}

		if ( six !== null ) {
			sixPos = six*positionHeight;
			t6d += "v" + sixPos + "h10v-" + sixPos + "h-10h10";
		}

	});

	document.getElementById("t1").setAttribute("d",t1d);
	document.getElementById("t2").setAttribute("d",t2d);
	document.getElementById("t3").setAttribute("d",t3d);
	document.getElementById("t4").setAttribute("d",t4d);
	document.getElementById("t5").setAttribute("d",t5d);
	document.getElementById("t6").setAttribute("d",t6d);

	focus = urlParams["club"].toUpperCase();
	team = clubs[focus];
	teamName = teams[focus];
	start = 50;
	p0 = 73 - positionHeight;
	line = "";
	started = false;
	current = p0;
	gap = 10;
	consecutive = 0;
	team.forEach(position=>{
		if ( position === null ) {
			if ( started ) {
				if ( consecutive === 1 ) {
					line += "l2,0";
					gap += 8;
				} else {
					gap += 10;
				}
			} else {
				start += 10;
			}
			consecutive = 0;
		} else {
			place = p0 + (position*positionHeight);
			if ( gap !== 10 ) {
				line += "m"+gap;
				diff = place - current;
				line += ","+diff;
				gap = 10;
			} else {
				if ( ! started ) {
					line += "M"+start+","+place;
					started = true;
				} else {
					diff = place - current;
					line += "l10,"+diff;
				}
			}
			current = place;
			consecutive++;
		}
	});
	if ( consecutive === 1 ) {
		line += "l2,0";
	}
	document.getElementById("POS").setAttribute("d",line);
	document.getElementById("title").innerHTML = teamName + " league history 1909-2025";
}

$(document).ready(function(){
	if ( urlParams["club"] ) {
    	buildGraph();
	}
});